/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: multikunst (https://sketchfab.com/multikunst)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/multi--moka--express--bialetti-illy-coffee-0fbbe71b76ba485fa11d516c270057e5
Title: Multi_ Moka_ Express_ Bialetti_ILLY_Coffee
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-350.023, 293.452, -1.62]} scale={[26.231, 26.231, 20.901]}>
          <mesh geometry={nodes.Plane_BLACK_0.geometry} material={materials.BLACK} />
          <mesh geometry={nodes.Plane_METAL_0.geometry} material={materials.METAL} />
        </group>
        <group position={[-351.124, 413.621, -1.18]} rotation={[-Math.PI / 2, 0, 0]} scale={119.006}>
          <mesh geometry={nodes.Cylinder003_BLACK_0.geometry} material={materials.BLACK} />
          <mesh geometry={nodes.Cylinder003_METAL_0.geometry} material={materials.METAL} />
        </group>
        <group position={[32.585, 0, 45.619]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder002_METAL_0.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Cylinder002_RED_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cylinder002_ILLY_LOGO_0.geometry} material={materials.ILLY_LOGO} />
        </group>
        <mesh geometry={nodes.Cylinder_METAL_0.geometry} material={materials.METAL} position={[-357.523, 0, 1.399]} rotation={[-Math.PI / 2, 0, 0]} scale={114.462} />
        <mesh geometry={nodes.Cylinder001_METAL_0.geometry} material={materials.METAL} position={[-357.523, 0.633, 1.399]} rotation={[-Math.PI / 2, 0, 0.383]} scale={116.409} />
        <mesh geometry={nodes.Cylinder004_METAL_0.geometry} material={materials.METAL} position={[32.585, 426.349, 45.619]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder005_Material005_0.geometry} material={materials['Material.005']} position={[-185.44, 79.269, 243.071]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder006_Material005_0.geometry} material={materials['Material.005']} position={[-188.82, 0, 245.65]} rotation={[-Math.PI / 2, 0, 0]} scale={70.991} />
        <mesh geometry={nodes.Cylinder007_COFFEE_0.geometry} material={materials.COFFEE} position={[-189.642, 118.345, 243.319]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['bi8162b6cf-bialetti-logo-bialetti-logo-png-5-transparent-images_BIALETTI_0'].geometry} material={materials.BIALETTI} position={[-359.796, 253.985, 116.172]} scale={54.859} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
