/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 deskSetupModel.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
export function DeskSetupModel(props) {
  const deskMesh=useRef();
  useFrame(({clock})=>{
    deskMesh.current.rotation.y=clock.getElapsedTime()*.25;
  })
  const { nodes, materials } = useGLTF('./assets/deskSetup/deskSetupModel.glb')
  return (
    <group {...props} ref={deskMesh} dispose={null}>
      <group position={[4.819, 1.444, -2.063]} rotation={[-1.4, -0.466, 0.007]} scale={4}>
        <mesh geometry={nodes.Cube_0.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cube001_0.geometry} material={materials.Wood} position={[2.35, 0, -1.49]} />
        <mesh geometry={nodes.Cube002_0.geometry} material={materials.Wood} position={[-2.35, 0, -1.49]} />
        <mesh geometry={nodes.Cube003_0.geometry} material={materials.Wood} position={[0, 0.8, -1.05]} />
        <mesh geometry={nodes.Cube004_0.geometry} material={materials.Wood} position={[-1.525, -1.25, -0.2]} />
        <mesh geometry={nodes.Cube005_0.geometry} material={materials.Wood} position={[1.525, -1.25, -0.2]} />
        <mesh geometry={nodes.Cube006_0.geometry} material={materials.Wood} position={[0, -1.25, -0.2]} />
        <mesh geometry={nodes.Cube007_0.geometry} material={materials.Wood} position={[-1.525, -0.29, -0.3]} />
        <mesh geometry={nodes.Cube008_0.geometry} material={materials.Wood} position={[0, -0.29, -0.3]} />
        <mesh geometry={nodes.Cube009_0.geometry} material={materials.Wood} position={[1.525, -0.29, -0.3]} />
        <mesh geometry={nodes.Cube010_0.geometry} material={materials.Wood} position={[-0.762, -0.213, -0.2]} />
        <mesh geometry={nodes.Cube011_0.geometry} material={materials.Wood} position={[0.762, -0.213, -0.2]} />
      </group>
      <group position={[0, 18.121, -0.77]} rotation={[-1.557, -0.288, -0.069]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Box001_���������_0'].geometry} material={materials.material} position={[1507.086, 2923.23, -259.844]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Box002_���������_0'].geometry} material={materials.material_2} position={[4105.512, -2793.306, 259.843]} />
          <mesh geometry={nodes['Box003_���������_0'].geometry} material={materials.material_2} position={[3014.173, -2793.306, 259.843]} />
          <mesh geometry={nodes['Box005_���������_0'].geometry} material={materials.material_2} position={[3559.842, -2793.306, 259.842]} />
          <mesh geometry={nodes['Box014_���������_0'].geometry} material={materials.material} position={[0, -4872.047, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Box015_������_0'].geometry} material={materials.material_3} position={[0, 1104.332, 116.929]} />
          <mesh geometry={nodes['Box016_���������_0'].geometry} material={materials.material_2} position={[5196.851, -2793.306, 259.843]} />
          <mesh geometry={nodes['Box017_���������_0'].geometry} material={materials.material_2} position={[0, -2403.543, 25.984]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Box018_���������_0'].geometry} material={materials.material_2} position={[4651.181, -2793.306, 259.843]} />
          <mesh geometry={nodes['Box019_���������_0'].geometry} material={materials.material} position={[0, -4742.126, -259.843]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Cylinder00_������������_0'].geometry} material={materials.material_1} position={[5586.614, -2793.306, 207.875]} />
          <mesh geometry={nodes['Cylinder01_���������_0'].geometry} material={materials.material} position={[5586.614, -2793.306, 207.875]} />
        </group>
      </group>
      <group position={[0.251, 5.727, 4.961]} rotation={[-0.648, -0.307, -0.819]} scale={3}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Big_Buttons} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Chassis} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Small_Buttons} />
      </group>
      <group position={[10.324, 9.352, -1.352]} rotation={[-0.978, 0.215, 0.451]} scale={0.4}>
        <group position={[0, 0, 0.169]} rotation={[Math.PI, 0, Math.PI]} scale={2.165}>
          <mesh geometry={nodes['Material-material'].geometry} material={materials['Material.003']} />
          <mesh geometry={nodes['Material_001-material'].geometry} material={materials['Material.001']} />
          <mesh geometry={nodes['Material_002-material'].geometry} material={materials['Material.002']} />
          <mesh geometry={nodes['Material_002-material001'].geometry} material={materials['Material.002']} />
          <mesh geometry={nodes['Material_005-material'].geometry} material={materials['Material.005']} />
          <mesh geometry={nodes['Material_008-material'].geometry} material={materials['Material.008']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./assets/deskSetup/deskSetupModel.glb')
