/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: Virtual Museums of Małopolska (https://sketchfab.com/WirtualneMuzeaMalopolski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sculpture-of-a-roman-gladiator-ca42e593d8aa4b2894dc2b288f595af5
Title: Sculpture of a Roman gladiator
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Roman(props) {
  const { nodes, materials } = useGLTF('./assets/roman/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.defaultMat} />
      </group>
    </group>
  )
}

useGLTF.preload('./assets/roman/scene.gltf')
