/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: yryabchenko (https://sketchfab.com/yryabchenko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/table-1132fa2850a24917892733566bd68e74
Title: Table
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Table(props) {
  const { nodes, materials } = useGLTF('./assets/table/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder6_blinn1_0.geometry} material={materials.blinn1} />
    </group>
  )
}

useGLTF.preload('./assets/table/scene.gltf')
