/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/volleyball-5ebd04ad8a9647e999c04ae92dd2fe13
Title: Volleyball
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Volleyball(props) {
  const { nodes, materials } = useGLTF('./assets/volleyball/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.003']} />
    </group>
  )
}

useGLTF.preload('./assets/volleyball/scene.gltf')
