version: "3"
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
      # args:
        #list out differnt args
    container_name: production
    ports:
      - "8080:80"
    