name: Lint and Test Code Base

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      app:
        image: docker.io/haydentinker/portfolio-website:latest
        ports:
          - "80:80"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose -f docker-compose-dev.yml up -d 

    - name: Run Unit Tests
      run: |
        docker-compose -f docker-compose.yml -f docker-compose-dev.yml exec react-app npm test 

    - name: Tear down Docker Compose
      run: docker-compose down  
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14   

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}